### ISSUE TITLE
Программная работа с функциональностью "Автоматизированное тестирование 1С"

### ISSUE THREAD

**Issue by alehinsasha** [MikhailMKZ/sb-course-1-final#4]
**В дополнение к проверке навыка "Создать свой шаг проверяющий текст предупреждения"**

Нужно реализовать свой шаг используя функциональность "Автоматизированное тестирование 1С" и свойство "ТестовоПриложение" переменной "КонтекстСохраняемый", который проверяет сообщения пользователю в момент проведения документа реализации товара. Например, если нет в сообщении текста "Не хватает товара" то реализация провелясь корректно. Или если есть текст "Не хватает товара" а товара действительно нет на остатках, то - Ок, функциональность контроля остатков проверена.

**Comment by MikhailMKZ** [comment]
Александр, у меня вопрос по реализации задачи.
Я через КонтекстСохраняемый получаю объект с типом "ТестируемоеОкноКлиентскогоПриложения" и с помощью метода ПолучитьТекстыСообщенийПользователю() анализирую тексты сообщений.
Но при проведении документа до вывода сообщений выводится окно с ошибкой
![image](https://cloud.githubusercontent.com/assets/18185319/19350698/7f9e7d52-9161-11e6-932b-11537b09e445.png)
Таким образом шаг теста падает с ошибкой 
![image](https://cloud.githubusercontent.com/assets/18185319/19350799/df90c878-9161-11e6-979f-f3e22a9aebfb.png)
Как я понимаю, окно платформы с ошибкой появляется раньше окна с сообщениями и я не понимаю как это программно обойти. Можете помочь?

**Comment by alehinsasha** [comment]
Получается в шаге проверки сообщений пользователю у вас "в руках" окно предупреждения. Нужно либо, рас окно предупреждения у вас уже "в руках" его закрыть и снова получить окно клиентского приложения и прочитать сообщения пользователю, любо ориентироваться на окно предупреждения, в данном случае если проверяем списание достаточного количества и появилось окно - значит ошибка, шаг должен упасть. А если остатков не достаточно и окно появилось - значит контроль остатков работает. А может у вас контроль остатков опциональный? Тогда...

**Comment by MikhailMKZ** [comment]
@alehinsasha , спасибо! Разобрался.
