### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [MikhailMKZ/sb-course-1-final#6]
В комментарии к этому issue напишите ваши:

* Имя Фамилию (в дательном падеже)
* Адрес электронной почты, на которую выслать сертификат

**Comment by MikhailMKZ** [comment]
@alehinsasha

Михаилу Миронову

xmikezx@gmail.com

**Comment by alehinsasha** [comment]
Поздравительное письмо отправлено на указанный адрес! Прошу подтвердить получение.

**Comment by MikhailMKZ** [comment]
@alehinsasha всё пришло, спасибо большое!

**Comment by alehinsasha** [comment]
Успехов!
